# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFeOOzz9jk_fLzXnIjTbDsb_7wk7Jor0
"""

import pandas as pd
aisles=pd.read_csv("aisles.csv")
aisles.head()

import pandas as pd
departments=pd.read_csv("departments.csv")
departments.head()

import pandas as pd
op=pd.read_csv("order_products__prior.csv")
op.head()

import pandas as pd
orders=pd.read_csv("orders.csv")
orders.head()

import pandas as pd
products=pd.read_csv("products.csv")
products.head()

# Copy original
aisles_clean = aisles.copy()

# Check missing values
print(aisles_clean.isnull().sum())

# Drop duplicates
aisles_clean = aisles_clean.drop_duplicates()

# Convert datatype
aisles_clean['aisle_id'] = aisles_clean['aisle_id'].astype(int)
aisles_clean['aisle'] = aisles_clean['aisle'].astype(str)

# Reset index
aisles_clean = aisles_clean.reset_index(drop=True)

# Final check
print(aisles_clean.info())

departments_clean = departments.copy()

# Missing values
print(departments_clean.isnull().sum())

# Drop duplicates
departments_clean = departments_clean.drop_duplicates()

# Fix datatypes
departments_clean['department_id'] = departments_clean['department_id'].astype(int)
departments_clean['department'] = departments_clean['department'].astype(str)

# Reset index
departments_clean = departments_clean.reset_index(drop=True)

print(departments_clean.info())

products_clean = products.copy()

# Missing values
print(products_clean.isnull().sum())

# Drop duplicates
products_clean = products_clean.drop_duplicates()

# Handle missing product names (if any)
products_clean['product_name'] = products_clean['product_name'].fillna("Unknown")

# Fix datatypes
products_clean['product_id'] = products_clean['product_id'].astype(int)
products_clean['aisle_id'] = products_clean['aisle_id'].astype(int)
products_clean['department_id'] = products_clean['department_id'].astype(int)

# Reset index
products_clean = products_clean.reset_index(drop=True)

print(products_clean.info())

orders_clean = orders.copy()

# Check missing values
print(orders_clean.isnull().sum())

# ❗ Drop rows where important columns are missing
orders_clean = orders_clean.dropna(subset=[
    'user_id',
    'order_number',
    'order_dow',
    'order_hour_of_day'
])

# Handle days_since_prior_order (this can be missing)
orders_clean['days_since_prior_order'] = orders_clean['days_since_prior_order'].fillna(0)

# Now convert datatypes safely
orders_clean['order_id'] = orders_clean['order_id'].astype(int)
orders_clean['user_id'] = orders_clean['user_id'].astype(int)
orders_clean['order_number'] = orders_clean['order_number'].astype(int)
orders_clean['order_dow'] = orders_clean['order_dow'].astype(int)
orders_clean['order_hour_of_day'] = orders_clean['order_hour_of_day'].astype(int)

# Drop duplicates
orders_clean = orders_clean.drop_duplicates()

# Reset index
orders_clean = orders_clean.reset_index(drop=True)

print(orders_clean.info())

aisles_clean.to_csv("clean_aisles.csv", index=False)
departments_clean.to_csv("clean_departments.csv", index=False)
products_clean.to_csv("clean_products.csv", index=False)
orders_clean.to_csv("clean_orders.csv", index=False)
op_clean.to_csv("clean_op.csv", index=False)

op_clean = op.copy()

# Check missing values
print(op_clean.isnull().sum())

# Drop duplicates
op_clean = op_clean.drop_duplicates()

# Fill missing values (important fix)
op_clean['add_to_cart_order'] = op_clean['add_to_cart_order'].fillna(0)
op_clean['reordered'] = op_clean['reordered'].fillna(0)

# Convert datatypes
op_clean['order_id'] = op_clean['order_id'].astype(int)
op_clean['product_id'] = op_clean['product_id'].astype(int)
op_clean['add_to_cart_order'] = op_clean['add_to_cart_order'].astype(int)
op_clean['reordered'] = op_clean['reordered'].astype(int)

# Reset index
op_clean = op_clean.reset_index(drop=True)

print(op_clean.info())

# Merge orders + order_products
df = orders_clean.merge(op_clean, on="order_id")

# Merge with products
df = df.merge(products_clean, on="product_id")

print(df.head())

# Take max order_number per user (proxy for recency)
recency = orders_clean.groupby('user_id')['order_number'].max().reset_index()
recency.columns = ['user_id', 'recency']

print(recency.head())

frequency = orders_clean.groupby('user_id')['order_id'].count().reset_index()
frequency.columns = ['user_id', 'frequency']

print(frequency.head())

monetary = op_clean.merge(orders_clean[['order_id', 'user_id']], on='order_id')

monetary = monetary.groupby('user_id')['product_id'].count().reset_index()
monetary.columns = ['user_id', 'monetary']

print(monetary.head())

rfm = recency.merge(frequency, on='user_id')
rfm = rfm.merge(monetary, on='user_id')

print(rfm.head())

aov = op_clean.merge(orders_clean[['order_id', 'user_id']], on='order_id')

aov = aov.groupby('user_id')['product_id'].count() / frequency['frequency']
aov = aov.reset_index()
aov.columns = ['user_id', 'avg_order_value']

print(aov.head())

rfm['clv'] = rfm['monetary'] * rfm['frequency']

print(rfm.head())

# Avg days between orders
purchase_trend = orders_clean.groupby('user_id')['days_since_prior_order'].mean().reset_index()
purchase_trend.columns = ['user_id', 'avg_days_between_orders']

print(purchase_trend.head())

final_df = rfm.merge(aov, on='user_id')
final_df = final_df.merge(purchase_trend, on='user_id')

print(final_df.head())
print(final_df.info())

final_df.to_csv("customer_features.csv", index=False)
